const advisoryData = {
  advisedCompanies: [
    {
      code: "ANK",
      companyName: "Ankra.io",
      companyType: "🇸🇪 Startup",
      companySector: "DevTools",
      companyLogo: "/images/clients/ankra.webp",
      companyLogoX: 200,
      companyLogoY: 500,
      companyUrl: "https://www.ankra.io",
      role: "Strategic Advisor",
      story: "Product strategy, testing, feature requests.",
      year: "2023",
      show: false 
    },     
    {
      code: "CDM",
      companyName: "CloudMe",
      companyType: "🇺🇸 Startup",
      companySector: "DevTools",
      companyLogo: "/images/clients/cloudme.webp",
      companyLogoX: 200,
      companyLogoY: 500,
      companyUrl: "https://www.cloudme.dev",
      role: "Strategic Advisor",
      story: "Product strategy, testing, feature requests.",
      year: "2023",
      show: false 
    }, 
    {
      code: "JGR",
      companyName: "Joggr",
      companyType: "🇺🇸 Startup",
      companySector: "DevTools",
      companyLogo: "/images/clients/joggr.webp",
      companyLogoX: 200,
      companyLogoY: 500,
      companyUrl: "https://www.joggr.io",
      role: "Strategic Advisor",
      story: "Product strategy, testing, feature requests.",
      year: "2023",
      show: false 
    },
    {
      code: "ZEF",
      companyName: "Zefi.ai",
      companyType: "🇮🇹 Startup",
      companySector: "Artificial Intelligence",
      companyLogo: "/images/clients/zefi.webp",
      companyLogoX: 200,
      companyLogoY: 500,
      companyUrl: "https://zefi.ai",
      role: "Strategic Advisor",
      story: "Infrastructure avisory, product testing, support for their AI platform.",
      year: "2023",
      show: false 
    },
    {
      code: "ZWA",
      companyName: "Zwap",
      companyType: "🇮🇹 Startup",
      companySector: "Social Network",
      companyLogo: "/images/clients/zwap.webp",
      companyLogoX: 200,
      companyLogoY: 500,
      companyUrl: "https://zwap.in",
      role: "Strategic Advisor",
      story: "Infrastructure avisory and operations on AWS EKS, product testing, feature requests.",
      year: "2022",
      show: false 
    },
    {
      code: "SPA",
      companyName: "Spation",
      companyType: "🇮🇹 Startup",
      companySector: "Coworking",
      companyLogo: "/images/clients/spation.webp",
      companyLogoX: 200,
      companyLogoY: 500,
      companyUrl: "https://app.spation.co",
      role: "Strategic Advisor",
      story: "Testing, feature requests.",
      year: "2021",
      show: false 
    },
    {
      code: "GRNC",
      companyName: "GreenChic",
      companyType: "Scaleup",
      companySector: "Sustainable Fashion",
      companyLogo: "/images/clients/greenchic.webp",
      companyLogoX: 80,
      companyLogoY: 80,
      companyUrl: "https://www.crunchbase.com/organization/wardrobe-green-armadio-verde",
      role: "Strategic Advisor",
      story: "Infrastructure avisory and operations on AWS.",
      year: "2021",
      show: false
    },       
  ]
}