const advisoryData = {
  advisedCompanies: [
    {
      code: "KSP",
      companyName: "Kubespaces.io",
      companyType: "🇳🇱 Startup",
      companySector: "DevTools",
      companyLogo: "/images/clients/kubespaces.webp",
      companyLogoX: 200,
      companyLogoY: 500,
      companyUrl: "https://kubespaces.io",
      role: "Trainer",
      story: "Kubernetes and GitOps training",
      year: "2023-2024",
      show: false 
    },
    {
      code: "WAY",
      companyName: "Wayy",
      companyType: "🇺🇸 Startup",
      companySector: "DevTools",
      companyLogo: "/images/clients/wayy.webp",
      companyLogoX: 200,
      companyLogoY: 500,
      companyUrl: "https://wayy.co/",
      role: "Strategic Advisor",
      story: "Product strategy, testing, feature requests for the new employee development co-pilot.",
      year: "2023",
      show: false
    },
    {
      code: "ANK",
      companyName: "Ankra.io",
      companyType: "🇸🇪 Startup",
      companySector: "DevTools",
      companyLogo: "/images/clients/ankra.webp",
      companyLogoX: 200,
      companyLogoY: 500,
      companyUrl: "https://www.ankra.io",
      role: "Strategic Advisor",
      story: "Product strategy, testing, feature requests for the Kubernetes automation platform.",
      year: "2023",
      show: false 
    },     
    {
      code: "CDM",
      companyName: "CloudMe",
      companyType: "🇺🇸 Startup",
      companySector: "DevTools",
      companyLogo: "/images/clients/cloudme.webp",
      companyLogoX: 200,
      companyLogoY: 500,
      companyUrl: "https://www.cloudme.dev",
      role: "Strategic Advisor",
      story: "Product strategy, testing, feature requests for the unopinionated platform to build and deploy cloud native applications.",
      year: "2023",
      show: false 
    }, 
    {
      code: "JGR",
      companyName: "Joggr",
      companyType: "🇺🇸 Startup",
      companySector: "DevTools",
      companyLogo: "/images/clients/joggr.webp",
      companyLogoX: 200,
      companyLogoY: 500,
      companyUrl: "https://www.joggr.io",
      role: "Strategic Advisor",
      story: "Product strategy, testing, feature requests for the first docOps AI powered platform.",
      year: "2023",
      show: false 
    },
    {
      code: "ZEF",
      companyName: "Zefi.ai",
      companyType: "🇮🇹 Startup",
      companySector: "Artificial Intelligence",
      companyLogo: "/images/clients/zefi.webp",
      companyLogoX: 200,
      companyLogoY: 500,
      companyUrl: "https://zefi.ai",
      role: "Strategic Advisor | Technical Advisor",
      story: "Infrastructure advisory, product testing, support for their AI platform helping Product Managers to take data-driven decisions.",
      year: "2023-now",
      show: true 
    },
    {
      code: "ZWA",
      companyName: "Zwap now Klaaryo",
      companyType: "🇮🇹 Startup",
      companySector: "Social Network",
      companyLogo: "/images/clients/zwap.webp",
      companyLogoX: 200,
      companyLogoY: 500,
      companyUrl: "https://zwap.in",
      role: "Strategic Advisor",
      story: "Infrastructure advisory and operations on AWS EKS, product testing, feature requests for their freelance social network.",
      year: "2022",
      show: false 
    },
    {
      code: "SPA",
      companyName: "Spation",
      companyType: "🇮🇹 Startup",
      companySector: "Coworking",
      companyLogo: "/images/clients/spation.webp",
      companyLogoX: 200,
      companyLogoY: 500,
      companyUrl: "https://app.spation.co",
      role: "Strategic Advisor",
      story: "Testing, feature requests for their coworking management platform.",
      year: "2021",
      show: false 
    },
    {
      code: "GRNC",
      companyName: "GreenChic",
      companyType: "Scaleup",
      companySector: "Sustainable Fashion",
      companyLogo: "/images/clients/greenchic.webp",
      companyLogoX: 80,
      companyLogoY: 80,
      companyUrl: "https://www.crunchbase.com/organization/wardrobe-green-armadio-verde",
      role: "Strategic Advisor",
      story: "Infrastructure advisory and operations on AWS for their sustainable fashion platform.",
      year: "2021-2022",
      show: false
    },       
  ]
}