/* Various data */

const userData = {
    githubUsername: "mbianchidev",
    name: "Matteo Bianchi",
    role: "DevOps | SRE | Coach | Developer",
    avatarUrl: "/images/propic.webp",
    mobileAvatarUrl: "/images/propic-mobile.webp",
    email: "info@mb-consulting.dev",
    privacyMail: "privacy@mb-consulting.dev",
    siteMail: "site@mb-consulting.dev",
    mailThankYouMessage: 
    {
        description: [
            `How are you? Hope everything is fine.`,
            `You are receiving this email because you have contacted me through my website (or someone used your email in my contact form)`,
            `You won't regret this! Every client may be former, new or potential matters a lot to me.`,
            `That's why it may take some time for me to respond. I carefully read every email and try to answer to all of them.`,
            `If I can't directly help you, I'll try to find someone who can in my network.`,
            `If you don't receive a reply from me within 72 hours, please check your spam folder or contact me again.`,
        ],
    },
    address: "Full remote",
    vat: "IT11846470968",
    sdi: "M5UXCR1",
    domain: "mb-consulting.dev",
    cookieUrl: "https://www.allaboutcookies.org/",
    about: {
        title: "A long time ago in a galaxy far, far away... I fell in ❤️ with DevOps culture, I became passionate about clouds 🌩️ and obsessed with IT security 🔐. Always eager to learn and teach new stuff, to make a difference",
        clickText: "Get to know me better 👇",
        story: {
            shortTitle: "DevOps: A Star Wars Story",
            description: [
                `My story was filled with monstrous bugs 🐞, amazing features ✨, large scale products ⛰️, many programming languages and frameworks 📚, huge infrastructures 🗼 and amazing colleagues 👨‍💻.`,
                `I changed my path from Software to the Dark Side by becoming a DevOps/SRE taking the best from both worlds (never stopped to use the --force).`,
                `I've started to coach and mentor my padawans (ehm I mean, fellow IT people) as I strongly believe that knowledge is the only way to grow both as a person and a professional.`,
                `In the time I've been in the IT industry, since 2017, I've learned a lot from both experience and people. The same knowledge that made me the engineer I am today I'm now willing to share with you.`,
                `I've seen and made many mistakes along the way but always learnt from them. Quoting Yoda: "The greatest teacher, failure is."`,
                `That is the reason I decided to start my journey as a freelance: to help people and companies to learn from their mistakes instead of avoiding them.`,
                `A few other things about me: I'm a remote worker 🏝️ and a Hybrid Digital Nomad™ ✈️🏡️ This means I will be reliable even if we live and work in different timezones!`,
                `In the last few years I've developed a strong interest in the world of finance 💲, cryptocurrencies and blockchain technologies.`,
                `I'm a combat sport amateur (boxe, K1, muay thai) 🥊 a musician/metal singer 🎹 and a passionate gamer 🕹️. I'm also a huge fan of Star Wars 🌌 and Lord of The Rings ⚔️. I play D&D 🎲 and cook italian dishes 🍝.`,
            ],
        },
        goals: {
            shortTitle: "My Jedi Code",
            description: [
                `My main goal is to enable DevOps culture in your company to add tons of value to your products and improve your developers experience.`,
                `In our time toghether we will build a strong bond, because trust is the foundation of every professional relationship.`,
                `I value communication over control, dialog rather than command, good design instead of "as long as it works", leaving a legacy above making myself indispensable, being safe more than being sorry, and being always kind not always right.`,
                `My framework enables your company to craft quality software because not only we are working toghether here and now but our efforts are going to be built to last.`,
                `What do I like most of my job?`,
                `Recommending the fresh techs (always production-ready), automating \& optimizing your processes (yes, cost optimization included 💸), spreading good practices and boosting your team(s) knowledge base so they become your dream team.`,
            ],
        },
        techs: {
            shortTitle: "Tech Stack & Lightsabers",
            description: [
                `I'm a polyglot developer, I love to learn new languages, frameworks and cloud technologies.`,
                `I'm a big fan of the following technologies:`,
            ],
            warning: "I'm not affiliated with nor endorsed by any of these companies, I've just used or am using some of their products."
        }

    },
    resumeUrl: "/static/Matteo_Bianchi_CV_smart.pdf",
    hero: {
        colors: ["#FF7F3F","#60A5FA","#A78BFA","#34D399"],
        funnySentences: [
            "This is definitely my fancy version, I usually wear shorts and a band t-shirt 😎",
            "Did you know I prefer Windows + WSL over Linux? 🤔",
            "Did you know I'm a big fan of the Star Wars universe? 🌌",
            "Did you know I'm a big fan of the Lord of The Rings universe? ⚔️",
            "Did you know I've been a metal singer for a couple of years? 🎤",
            "Did you know I'm a combat sport amateur? 🥊",
            "Did you know I'm a huge fan of D&D (3.5 or 5th, 4 is not my jam)? 🎲",
            "Spaghetti code? I prefer pasta with ragù sauce 🍝",
            "My favorite drink is a pint of beer 🍺, what's yours?",
            "I'm not a football fan, I prefer rugby 🏉. What's your favorite sport?",
            "Yes, I've got tattos 🤘 (coverable, don't worry) and why should you worry anyway?",
            "My favorite film (or one of) is Gran Torino 🎥, what's yours?",
            "Yes, I've got stretched lobes. I'm a metalhead 🤘",
            "I do electronic music production 🎹, what's your favorite genre?",
            "One of my favourite games is The Witcher 3 🕹️, what's yours?",
            "Dear JavaScript, 0.1+0.2=0.30000000000000004, I'm not mad, just very disappointed.",
            "Docker enters in a bar, the bartender says: 'We don't serve containers here'.",
            "A DevOps, a SRE and a SysAdmin walk into a bar. The bartender says: 'What is this, some kind of joke?'",
            "Java is to JavaScript as car is to carpet.",
            "Confucio says 'Before you yell at your team, walk a mile in their shoes'.",
            "Sun Tzu said 'If you know the enemy and know yourself, you need not fear the result of a hundred deploys'.",
            "'I'm not a great programmer; I'm just a good programmer with great habits' - Kent Beck",
            "There are no 'best practices', just good ones.",
            "The best way to learn is to teach 👨‍🏫",
            "PHP since 8.0 is not that bad, I just don't like it.",
            "To write a recursive function you must first define a recursive function",
            "What does a SysAdmin say to a DevOps? 'Luke, I'm your father!'",
            "SREs are like Jedi Knights, they are the guardians of the force.",
            "What would you do with a million dollars? I'd invest them (crypto included) 💵",
            "C++ is C with classes. Prove me wrong 😎",
            "echo 'Hello World'",
            "awk is like sed, but more powerful.",
            "No quote today, I'm too tired 🥱",
            "G note is the best note.",
            "I'm not a drummer but I air drum 🥁",
            "How many SysAdmins does it take to change a lightbulb? None, they just tell the lightbulb to change itself 💡",
            "Have you got time to talk about our lord and saviour, the Cloud? ☁️",
            "I don't know what to put here, I'm not a comedian (yet).",
            "Have you ever tried to eat a clock? It's very time consuming 🕑",
            "I Google everything 🔍",
            "Once a PM said to me: 'I GANTT take this anymore.' 😫",
            "Stackoverflow is my best friend.",
            "How many times have you reloaded the page? I've lost count.",
            "Play the Stanley Parable, it's a great game.",
            "Waterfall? I prefer to swim 🏊‍♂️",
            "I'm not a coffein addict, but I drink a lot of coffee ☕",
            "And the winner is ...",
            "The best code is no code at all.",
        ],
        firstPrinciple: "Craft.",
        firstLink: "/service/software-engineering",
        secondPrinciple: "Automate.",
        secondLink: "/service/devops-adoption-path",
        thirdPrinciple: "Secure.",
        thirdLink: "/service/sre-devsecops",
        fourthPrinciple: "Innovate.",
        fourthLink: "/service/cto-as-a-service",
        CTAs: ["Let's talk!", "Work with me!", "Need a DevOps?", "Looking for a CTO?", "Go cloud!", "Don't click here!", "Grab your free call!"],
    },
    // see next.config.js
    techStack: "/stack",
    socialLinks: {
        twitter: "/twitter",
        linkedin: "/linkedin",
        github: "/github",
        medium: "/blog",
        linktree: "/all-links",
    },
    projects: [
        {
            title: "Portfolio website",
            link: "https://github.com/mbianchidev/site",
            imgUrl: "/images/this-site.webp",
        },
        {
            title: "DevOps Basics Course for companies",
            link: "https://mb-consulting.dev/workinprogress",
            imgUrl: "/images/devops-course-table-of-contents.webp",
        }
    ],
};

export default userData;
