/* 
{
    companyName: "Company name",
    companyType: ["Corporate", "Startup", "Scaleup"...],
    companySector: ["Finance", "Healthcare", "Automotive"...],
    companyLogo: "/images/employers/company.webp",
    companyLogoX: logo width,
    companyLogoY: logo height,
    companyUrl: "https://acme.com",
    role: "What was your role?",
    story: "Details about the role and the company",
    year: "years of employment",
    show: true|false
},
*/

const experiencesData = {
  experiences: [
    {
      code: "KBLAB",
      companyName: "KubeLab",
      companyType: "Startup",
      companySector: "Cloud Native & DevOps",
      companyLogo: "/images/clients/kubelab.webp",
      companyLogoX: 187,
      companyLogoY: 62,
      companyUrl: "https://www.kubelab.cloud/",
      role: "Chief Technology Officer",
      story: "I joined KubeLab as CTO because I believe in its values, our aim is to enable people and businesses to make a positive impact on the world, through technology. My effort towards our clients is to be the bridge that fills the distance between their business needs and our technology solutions. My effort towards my team is to enable their full potential and ensure a smooth developer experience.",
      year: "2022-now",
      show: true
    },
    {
      code: "KBLAB",
      companyName: "KubeLab",
      companyType: "Startup",
      companySector: "Cloud Native & DevOps",
      companyLogo: "/images/clients/kubelab.webp",
      companyLogoX: 187,
      companyLogoY: 62,
      companyUrl: "https://www.kubelab.cloud/",
      role: "Freelance Consultant",
      story: "I partnered with KubeLab to help them to shape their company.",
      year: "2022",
      show: true
    },
    {
      code: "ROAR",
      companyName: "Roar",
      companyType: "Corporate",
      companySector: "Customer Experience (CX)",
      companyLogo: "/images/clients/roar.webp",
      companyLogoX: 187,
      companyLogoY: 48,
      companyUrl: "https://roarinc.com/",
      role: "Freelance DevOps Engineer | Site Reliability Engineer",
      story: "Collaborated with Roar to enable DevOps culture in all aspects of the company, starting with CI/CD processes on Azure DevOps. Responsible for the DevOps culture and the overall quality of the company's cloud infrastructure.",
      year: "2022",
      show: true
    },
    {
      code: "CPLS",
      companyName: "Coopolis",
      companyType: "Cooperative",
      companySector: "Facility management and public services",
      companyLogo: "/images/clients/coopolis.webp",
      companyLogoX: 187, //305,
      companyLogoY: 75, //122,
      companyUrl: "https://coopolis.it/",
      role: "Freelance Coach (DevOps)",
      story: "Enabled them to better understand IT DevOps culture by teaching classes with in-depth focus on Gitlab and CI/CD processes.",
      year: "2022",
      show: true
    },
    {
      code: "GRNC",
      companyName: "GreenChic",
      companyType: "Scaleup",
      companySector: "Sustainable Fashion",
      companyLogo: "/images/clients/greenchic.webp",
      companyLogoX: 80,
      companyLogoY: 80,
      companyUrl: "https://greenchic.it/",
      role: "Freelance DevOps Engineer | Site Reliability Engineer",
      story: "Built part of a new cloud infrastructure for their sustainable fashion e-commerce and hardened their security policies. I was also responsible for the health and security of the whole AWS infrastructure.",
      year: "2021-2022",
      show: true
    },
    {
      code: "GDF",
      companyName: "Italian Financial Police",
      companyType: "Public Administration",
      companySector: "Security and finance",
      companyLogo: "/images/clients/gdf.webp",
      companyLogoX: 125,
      companyLogoY: 75,
      companyUrl: "https://www.gdf.gov.it/",
      role: "Freelance Coach (DevOps)",
      story: "Helped their IT sector to improve DevOps practices by delivering a DevOps course and in-depth technical knowledge on Azure.",
      year: "2021",
      show: true
    },
    {
      code: "MVCTCH",
      companyName: "MVC Technologies S.p.A.",
      companyType: "Corporate",
      companySector: "IT Consultancy & education",
      companyLogo: "/images/clients/mvc.webp",
      companyLogoX: 190,
      companyLogoY: 49,
      companyUrl: "https://www.mvc-technology.eu/",
      role: "Freelance Coach (DevOps)",
      story: "Delivered DevOps course to one of their clients helping them to better understand the DevOps culture.",
      year: "2021",
      show: true
    },
    {
      code: "DSHR",
      companyName: "D-Share",
      companyType: "Corporate",
      companySector: "Digital News and Media",
      companyLogo: "/images/clients/dshare.webp",
      companyLogoX: 190,
      companyLogoY: 48,
      companyUrl: "https://www.dshare.com/",
      role: "Freelance DevOps Engineer | Site Reliability Engineer",
      story: "Managed Azure and AWS infrastructures for their news and media platform and digital products. I was responsible for the infrastructure, deployments, security and everything about the cloud.",
      year: "2021-2022",
      show: true
    },
    {
      companyName: "Infocert",
      companyType: "Corporate",
      companySector: "Digital Trust Services",
      companyLogo: "/images/employers/infocert.webp",
      companyLogoX: 338,
      companyLogoY: 150,
      companyUrl: "https://gosignweb.infocert.it",
      role: "Senior Software Engineer | DevOps Engineer | Site Reliability Engineer",
      story: "I brought DevOps in a digital signature product used by thousands of people and companies all over Europe: GoSign. I managed to improve the reliability and security of the product by developing document management processes in Java and by automating infrastructure provisioning, deployment, delivery and incident management processes.",
      year: "2019-2021",
      show: true
    },
    {
      companyName: "Eco-Mind Software",
      companyType: "Medium size company",
      companySector: "IT Consulting",
      companyLogo: "/images/employers/ecomind.webp",
      companyLogoX: 250,
      companyLogoY: 81,
      companyUrl: "https://eco-mind.eu/",
      role: "Senior Software Engineer",
      story: "Improved my Spring and Java skills by working side by side with valuable professionals both internal and external to the company. Here I learnt the true meaning of the word 'teamwork' and how to work in a team with a diverse set of skills.",
      year: "2018-2021",
      show: true
    },
    {
      companyName: "Reply Power",
      companyType: "Corporate",
      companySector: "IT Consulting",
      companyLogo: "/images/employers/reply.webp",
      companyLogoX: 510,
      companyLogoY: 94,
      companyUrl: "https://www.reply.com/it/content/smart-seller",
      role: "Fullstack Software Developer",
      story: "Got in touch with modern frontend and backend frameworks (Spring and Angular) for the first time. I was able to learn how to use them and how to build reusable components. This was also the first time i got in touch with DevOps culture and started my journey torwards my objective to become a DevOps engineer.",
      year: "2018",
      show: true
    },
    {
      companyName: "Vodafone",
      companyType: "Corporate",
      companySector: "Internet Provider & Telecomunication Services",
      companyLogo: "/images/employers/vodafone.webp",
      companyLogoX: 225,
      companyLogoY: 150,
      companyUrl: "https://www.vodafone.com/",
      role: "Fullstack Software Developer",
      story: "I worked on a product that was used by the financial group of Vodafone. Here I learnt the importance of refactoring, optimization and keeping up to date with techs. I also learnt how to work in a team and how to work in a fast-paced environment and how to manage a complex IT infrastructure.",
      year: "2017-2018",
      show: true
    },
    {
      companyName: "tenutabene (ex Cambiomarcia)",
      companyType: "Startup",
      companySector: "Automotive",
      companyLogo: "/images/employers/tenutabene.webp",
      companyLogoX: 289,
      companyLogoY: 36,
      companyUrl: "https://www.tenutabene.it/",
      role: "Fullstack Software Developer",
      story: "I learnt how a startup works and scales up and started my journey in the web development world.",
      year: "2017",
      show: true
    }
  ],
};

export default experiencesData;