/* 
{
  category: "Service macro category",
  name: "Service name",
  coverImage: "/images/services/service.webp",
  images: [
    {
      url: "/images/services/data1.webp",
      altText: "Some alt text",
      imageX: 500,
      imageY: 400,
      description: "Some image description",
    },
    ...
  ],
  slug: "slug-for-the-service",
  shortDescription: "one-phrased description of the service",
  description: [
      `Service description`,
      `Multiline`,
      ...
  ],
  CTA: 'call to action text',
  type: 'brief service description',
  active: true|false,
  offer: 'special offers for the service' | null | default: 'Free introductory call, first activity analysis and first activity estimate are billed at a discounted rate',
  rate: 'starting from X €' | 'X-Y €' | 0 | default: 'To be discussed',
},
*/

const servicesData = {
  basePath: '/service',
  services: [
    {
      category: "Coaching",
      name: "Modern DevOps Adoption",
      coverImage: "/images/service/devops-path.webp",
      images: [
        {
          url: "/images/service/devops-path-modules.webp",
          altText: "DevOps Adoption Path learning modules list",
          imageX: 500,
          imageY: 400,
          description: "Course learning core modules",
        },
        {
          url: "/images/service/devops-path-prices.webp",
          altText: "DevOps Adoption Path pricing",
          imageX: 500,
          imageY: 400,
          description: "DevOps Adoption Path packages",
        },
        {
          url: "/images/service/devops-path-support.webp",
          altText: "DevOps Adoption Path support options",
          imageX: 500,
          imageY: 400,
          description: "DevOps Adoption Path support options",
        },
      ],
      slug: "modern-devops-adoption",
      shortDescription: "A Modern DevOps approach",
      description: [
        `The focus of this service is starting a full DevOps adoption to make you able to deliver your software product faster and with a much higher quality..`,
        `The service will be delivered in three different phases: Assessment, Training, Support`,
        `The assessment phase is aimed at understanding your current situation, in terms of both DevOps maturity and overall technical process maturity.`,
        `I will need you to take a comprehensive Technical Maturity Assessment: a series of questionnaires that will help me understand your current situation.`,
        `The training phase starts with a modular and tailored training course and finishes with a roadmap guiding you torwards your next steps.`,
        `The support phase is aimed at helping you implementing key items of that roadmap and reach your goals quicker.`,
        `Modern DevOps Adoption is offered in different packages with different levels of training and support.`,
        `Basic - For small companies or individuals who want to learn about DevOps. Includes: 3-days core course and essential support package.`,
        `Intermediate - For small to medium companies and startups that want to go in depth with DevOps. Includes: 5-days core course and premium support package.`,
        `Advanced - For companies that want to start or consolidate their adoption process and reach a high level of maturity. Includes: 5-days core course, 2-days focused course and enterprise support package.`,
      ],
      callout: 'Are you ready to become the next DevOps star to be?',
      CTA: 'Sign up!',
      type: 'Training (available on-site) and support (remote only)',
      active: true,
      offer: null,
      rate: 'See carousel.',
    },
    {
      category: "Cloud",
      name: "Cloud - K8s - DevOps",
      coverImage: "/images/service/cloud-management.webp",
      images: [
        {
          url: "/images/service/cloud-management.webp",
          altText: "Cloud Management service image",
          imageX: 500,
          imageY: 400,
          description: "Cloud Management",
        },
      ],
      slug: "cloud-k8s-and-devops",
      shortDescription: "Scale up your business to the cloud ",
      description: [
        `Cloud is not easy, it requires a lot of knowledge and experience to be able to manage it properly.`,
        `Picking the right provider, the right services (IaaS, PaaS, SaaS), mixing public and private clouds, optimizing costs (FinOps) and so on.`,
        `I can:`,
        `- Understand what services suits your need and show you how to leverage them;`,
        `- Migrate your workloads to the cloud;`,
        `- Design and implement infrastructure - Infrastructure as Code (IaC);`,
        `- Manage your Kubernetes;`,
        `- Create pipelines and CI/CD from 0 to GitOps;`,
        `- Improve your workloads efficiency and optimize costs;`,
        `All of this, wether you are just starting your cloud journey or you already been in for a while.`,
      ],
      callout: 'It is time to get the most out of your cloud.',
      CTA: 'Schedule a meeting today!',
      link: '/book30',
      type: '6+ months of support (remote only).',
      active: true,
      offer: '25% discount for elegible startups.',
      rate: 'starting from 150/h',
    },
    {
      category: "Cloud",
      name: "Ops Security & SRE Review",
      coverImage: "/images/service/devsecops-sre-2.webp",
      images: [
        {
          url: "/images/service/devsecops-sre-frequency.webp",
          altText: "Frequency of cyber-attacks",
          imageX: 500,
          imageY: 400,
          description: "Frequency of attacks is increasing",
        },
        {
          url: "/images/service/devsecops-sre-cost-percentage.webp",
          altText: "Revenue lost due to security breaches in percentage",
          imageX: 500,
          imageY: 400,
          description: "The cost of attacks isn't limited to the direct damage",
        },
        {
          url: "/images/service/devsecops-sre-distribution.webp",
          altText: "Distribution of attacks in different industries",
          imageX: 500,
          imageY: 400,
          description: "Your reputation is at stake",
        },
        {
          url: "/images/service/devsecops-sre-time.webp",
          altText: "SRE & DevSecOps service image",
          imageX: 500,
          imageY: 400,
          description: "Your clients are at risk",
        },
        {
          url: "/images/service/devsecops-sre-money.webp",
          altText: "SRE & DevSecOps money lost due to security breaches",
          imageX: 500,
          imageY: 400,
          description: "You can't afford to ignore security",
        },
        {
          url: "/images/service/devsecops-sre-chain.webp",
          altText: "SRE & DevSecOps solution chain",
          imageX: 500,
          imageY: 400,
          description: "Your sec is only as strong as the weakest link",
        },
      ],
      slug: "sre-devsecops",
      shortDescription: "Discover how to secure your product and your success",
      description: [
        `DevSecOps and Site Reliability processes will improve the way you handle software, increasing both the stability and security of your product`,
        `I will perform a complete security review to identify the current security risks and vulnerabilities in both your software and cloud infrastructure.`,
        `I will then provide a list of recommendations and a roadmap to fix them.`,
        `Some examples of the most common security issues that I was able to identify:`,
        `- Exposed passwords, secrets, API keys and private keys; insecure protocols; weak auth; loose network policies; vulnerable containers and dependencies;`,
        `After that I will perform a complete reliability review to identify the current reliability issues and bottlenecks.`,
        `I will provide you with the tools to gain metrics from code and infra, to monitor and alert your team when something goes wrong.`,
        `These are the most common reliability issues I've encountered:`,
        `- High and unjustified resource usage; overprovisioning; poor infrastructure design and configuration; poor software design and architecture; inefficient database queries; non-redundant data storage; inefficient caching strategies; insufficient logging, monitoring and alerting;`,
        `Your Incident Management processes will be enhanced and you will see a drop in TTR (Time To Recovery).`,
        `Compliance with GDPR, PCI-DSS, ISO 27001, NIST, etc. compliance will be easier to achieve.`,
        `Security won't be an optional feature no more, it will become a mindset. Do not limit your company at having a security door, make it a fortress.`,
      ],
      callout: 'Is cybersecurity a priority for you?',
      CTA: 'Contact me!',
      type: 'on call support or 3+ months of support (remote only).',
      active: true,
      offer: null,
      rate: 'starting from 150/h',
    },
    {
      category: "Management",
      name: "CTO as a Service",
      coverImage: "/images/service/cto-as-a-service.webp",
      images: [
        {
          url: "/images/service/cto-as-a-service.webp",
          altText: "My photo looking at the camera while smiling",
          imageX: 500,
          imageY: 400,
          description: "I run the tech, you run the business",
        },
      ],
      slug: "cto-as-a-service",
      shortDescription: "Benefit from my fractional CTO services",
      description: [
        `Are you a startup in need of a CTO but you can't afford a full-time one? I got you covered.`,
        `Is your CTO overloaded with tasks and you need someone to help him? I will be his right hand (or left)`,
        `Are you planning to build an IDP to enable your developers to be more productive? I will help you with that.`,
        `I have guided companies from the early stages of their product to the final release and beyond.`,
        `Product Roadmaps, Architectures, Interviews, Team Management, Documentation, Budgeting, etc.`,
        `I can help you with all of that and more. I will be your CTO for a fraction of the cost of a full-time one`,
      ],
      callout: 'Sounds good?',
      CTA: 'Let\'s connect!',
      type: '6+ months of support (remote only).',
      active: true,
      offer: "25% discount off the 1st month of support, FREE consulting call included.",
      rate: 'starting from 200/h',
    },
    {
      category: "Cloud",
      name: "DevEx as a Service",
      coverImage: "/images/service/software.webp",
      images: [
        {
          url: "/images/service/software.webp",
          altText: "People working at a table",
          imageX: 500,
          imageY: 400,
          description: "Software Engineering but tailored as you need it",
        },
      ],
      slug: "devex-as-a-service",
      shortDescription: "Developer Experience made easy",
      description: [
        `DevEx, Platform Engineering and IDPs are fundamental for your company to scale.`,
        `No one wants to deal with messy spaghetti code, copy-pasted templates, obscure configurations or intricate deployments.`,
        `You are probably wasting a lot of time and money for maintenance, bug fixing and cloud costs. Instead of focusing on innovation.`,
        `I can help you to improve your DevOps processes to the point where your developers will be happy to work. How? By adopting or creating an IDP.`,
        `Adoption of an IDP will be fundamental, I will basically run a startup inside your main business where the customers will be your engineers.`,
        `I will be responsible for the design, development, maintenance and support of the IDP.`,
      ],
      callout: 'Ready to turn your company into a Platform powerhouse?',
      type: '6+ months of support (remote only).',
      CTA: 'Get in touch!',
      active: true,
      offer: null,
      rate: 'Starting from 150/h',
    },
    {
      category: "Coaching",
      name: "Mentoring and advisory",
      coverImage: "/images/service/other.webp",
      images: [
        {
          url: "/images/service/other.webp",
          altText: "Mentoring services image",
          imageX: 500,
          imageY: 400,
          description: "Mentoring for individuals, advisory for companies",
        },
      ],
      slug: "mentoring-services",
      shortDescription: "For anything else you need",
      description: [
        `I'm available for 1:1 mentoring:`,
        `- Career Coaching`,
        `- Mock interviews`,
        `- CV review`,
        `- Career Pathing`,
        ``,
        `Advisory services for companies:`,
        `- Technical Advisory`,
        `- Technical Debt Assessment`,
        ``,
        `For my mentoring services I use MentorCruise, a verified platform that allows me easily to manage my mentoring sessions.`,
      ],
      callout: 'I\'m open to new ideas and challenges you may have. We can talk always about it!',
      type: null,
      CTA: 'Let\'s work it out.',
      link: '/mentor',
      active: true,
      offer: null,
      rate: 'Starting from 90/h for individuals.',
    },
  ],
};

export default servicesData;