/*
    {
        name: "Name",
        image: "/images/techs/tech.webp",
        url: "https://awesome-product.com",
        x: icon width,
        y: icon height,
        level: "expertise level 1 to 100", //future use?
        show: true|false,
    },
*/

const techsData = {
  techs: [
    {
      name: "Git",
      description: "The king of VCS tools. I can't imagine working without it.",
      image: "/images/techs/git.webp",
      url: "https://git-scm.com",
      x: 80,
      y: 80,
      level: "85",
      show: true,
    },
    {
      name: "GitHub",
      description: "Since Microsoft bought GitHub, it has become quite a tool. I use it for my personal and OSS projects.",
      image: "/images/techs/github.webp",
      url: "https://github.com",
      x: 80,
      y: 80,
      level: "80",
      show: true,
    },
    {
      name: "GitLab",
      description: "Great tool for enterprise repositories and DevOps processes. A bit pricy.",
      image: "/images/techs/gitlab.webp",
      url: "https://about.gitlab.com",
      x: 100,
      y: 100,
      level: "90",
      show: true,
    },
    {
      name: "Amazon Web Services",
      description: "The most popular cloud provider (for a reason) and the one I use the most.",
      image: "/images/techs/aws.webp",
      url: "https://aws.amazon.com",
      x: 80,
      y: 50,
      level: "70",
      show: true,
    },
    {
      name: "Microsoft Azure",
      description: "At first I hated it, but I learnt to like it. It's a great tool for DevOps processes. The enterprise support is 'meh'.",
      image: "/images/techs/azure.webp",
      url: "https://azure.microsoft.com",
      x: 80,
      y: 80,
      level: "75",
      show: true,
    },
    {
      name: "Google Cloud Platform",
      description: "Used it a few times for experiments and I think it has a great potential. I quite like the pricing model.",
      image: "/images/techs/gcp.webp",
      url: "https://cloud.google.com",
      x: 80,
      y: 80,
      level: "65",
      show: true,
    },
    {
      name: "Docker",
      description: "Docker (and containerization) was a game changer for me. I use it for almast all of my projects.",
      image: "/images/techs/docker.webp",
      url: "https://www.docker.com",
      x: 80,
      y: 80,
      level: "75",
      show: true,
    },
    {
      name: "Kubernetes",
      description: "K8s is love and hate. I love it for its flexibility and hate it for the same reason.",
      image: "/images/techs/kubernetes.webp",
      url: "https://kubernetes.io",
      x: 80,
      y: 80,
      level: "70",
      show: true,
    },
    {
      name: "Helm",
      description: "Great tool for managing Kubernetes deployments but don't take it too far with templates.",
      image: "/images/techs/helm.webp",
      url: "https://helm.sh",
      x: 80,
      y: 80,
      level: "65",
      show: true,
    },
    {
      name: "Terraform", // FIXME remove terraform in favor of open-tf
      description: "My favorite IaC tool. It's kinda easy to use and it's very flexible.",
      image: "/images/techs/terraform.webp",
      url: "https://www.terraform.io",
      x: 80,
      y: 80,
      level: "70",
      show: true,
    },
    {
      name: "Puppet",
      description: "Good configuration management software. I used it for a few years and I ejoyed every puppet apply so far.",
      image: "/images/techs/puppet.webp",
      url: "https://puppet.com",
      x: 80,
      y: 80,
      level: "80",
      show: false,
    },
    {
      name: "Ansible",
      description: "I even took an official RedHat exam for this! I like it, but I prefer Terraform.",
      image: "/images/techs/ansible.webp",
      url: "https://ansible.com",
      x: 80,
      y: 80,
      level: "60",
      show: true,
    },
    {
      name: "AWS CloudFormation",
      description: "Great tool for managing AWS resources, of course it's not as flexible as Terraform and you know: vendor lock-in.",
      image: "/images/techs/aws-cloudformation.webp",
      url: "https://aws.amazon.com/cloudformation",
      x: 80,
      y: 80,
      level: "65",
      show: true,
    },
    {
      name: "New Relic",
      description: "I recommend it for monitoring your applications. It's very easy to use compared to other tools and it has a great UI. It's not free though.",
      image: "/images/techs/newrelic.webp",
      url: "https://newrelic.com",
      x: 80,
      y: 80,
      level: "80",
      show: true,
    },
    {
      name: "Fluentd",
      description: "Logging and metrics are SO important and Fluentd is a great tool for collecting those.",
      image: "/images/techs/fluentd.webp",
      url: "https://www.fluentd.org",
      x: 80,
      y: 80,
      level: "70",
      show: true,
    },
    {
      name: "SumoLogic",
      description: "Logs and metrics can be a mess but Sumo helps a lot!",
      image: "/images/techs/sumologic.webp",
      url: "https://www.sumologic.com",
      x: 80,
      y: 80,
      level: "75",
      show: true,
    },
    {
      name: "Atlassian OpsGenie",
      description: "I've been waking up to OpsGenie alerts for a few years now. Unfortunately works so well that SREs don't sleep anymore.",
      image: "/images/techs/opsgenie.webp",
      url: "https://www.atlassian.com/software/opsgenie",
      x: 80,
      y: 80,
      level: "70",
      show: true,
    },
    {
      name: "Atlassian StatusPage",
      description: "A really nice addition to your incident management process. Remember to close the page when you're done!",
      image: "/images/techs/statuspage.webp",
      url: "https://www.atlassian.com/software/statuspage",
      x: 80,
      y: 80,
      level: "70",
      show: true,
    },
    {
      name: "Jenkins",
      description: "A great CI/CD tool, rich ecosystem and a lot of plugins. 8/10 would recommend.",
      image: "/images/techs/jenkins.webp",
      url: "https://www.jenkins.io",
      x: 80,
      y: 80,
      level: "85",
      show: true,
    },
    {
      name: "GitHub Actions",
      description: "They improved a lot since the first release, it has a great integration with GitHub (duh), free tier is nice.",
      image: "/images/techs/github-actions.webp",
      url: "https://github.com/features/actions",
      x: 80,
      y: 80,
      level: "70",
      show: true,
    },
    {
      name: "NGINX",
      description: "Favourite ingress controller, it's fast and it's easy to configure even if you are not a sysadmin.",
      image: "/images/techs/nginx.webp",
      url: "https://www.nginx.com",
      x: 80,
      y: 80,
      level: "65",
      show: true,
    },
    {
      name: "Bash scripting",
      description: "Easy to learn, hard to master. I use it when I need to automate something quickly (but then I refactor I swear).",
      image: "/images/techs/bash.webp",
      url: "https://www.gnu.org/software/bash",
      x: 80,
      y: 80,
      level: "70",
      show: true,
    },
    {
      name: "SonarQube",
      description: "Want to scan your code? You should and Sonar is cool, SAST ftw.",
      image: "/images/techs/sonarqube.webp",
      url: "https://www.sonarqube.org",
      x: 80,
      y: 80,
      level: "70",
      show: true,
    },
    {
      name: "JFrog Artifactory",
      description: "Store everything in here but please organize it and don't think it's a reliable backup, thanks.",
      image: "/images/techs/artifactory.webp",
      url: "https://jfrog.com/artifactory",
      x: 80,
      y: 80,
      level: "70",
      show: true,
    },
    {
      name: "MYSQL",
      description: "Well, it's a database. It's not the best but it's not the worst. Super easy though.",
      image: "/images/techs/mysql.webp",
      url: "https://www.mysql.com",
      x: 80,
      y: 80,
      level: "80",
      show: false,
    },
    {
      name: "PostgreSQL",
      description: "Good performance, good features, good community, CloudNativePG runs on K8s. Amazing.",
      image: "/images/techs/postgresql.webp",
      url: "https://www.postgresql.org",
      x: 80,
      y: 80,
      level: "70",
      show: true,
    },
    // TODO add Golang
    {
      name: "Java",
      description: "My first programming language, I still love it. It's a fantastic choice for enterprise applications and with new developments like Quarkus it's even better.",
      image: "/images/techs/java.webp",
      url: "https://www.java.com",
      x: 80,
      y: 80,
      level: "80",
      show: true,
    },
    {
      name: "Spring Framework",
      description: "Mother of all Java frameworks, it's just a MUST.",
      image: "/images/techs/spring.webp",
      url: "https://spring.io",
      x: 80,
      y: 80,
      level: "80",
      show: true,
    },
    {
      name: "Python",
      description: "No I don't use it for machine learning (I'm not a data scientist either), I use it for automation and APIs.",
      image: "/images/techs/python.webp",
      url: "https://www.python.org",
      x: 80,
      y: 80,
      level: "60",
      show: true,
    },
    {
      name: "NextJS",
      description: "This site is built with NextJS and even if I'm not a frontend developer I kinda managed to make it work.",
      image: "/images/techs/nextjs.webp",
      url: "https://nextjs.org",
      x: 80,
      y: 80,
      level: "60",
      show: true,
    },
    {
      name: "Vercel",
      description: "Kudos to Vercel for making it so easy to deploy a NextJS site with so many features on top of that.",
      image: "/images/techs/vercel.webp",
      url: "https://vercel.com/features/infrastructure ",
      x: 80,
      y: 80,
      level: "75",
      show: true,
    },
    {
      name: "Postman",
      description: "I can't test my APIs without it, it's free, easy to setup and has a really nice UI.",
      image: "/images/techs/postman.webp",
      url: "https://www.postman.com",
      x: 80,
      y: 80,
      level: "80",
      show: true,
    },
    {
      name: "OpenAPI",
      description: "Adopt a standard for your APIs and you(r employees) will be happy.",
      image: "/images/techs/openapi.webp",
      url: "https://www.openapis.org",
      x: 80,
      y: 80,
      level: "70",
      show: true,
    },
  ],
};

export default techsData;