const heroData = {
  hero: {
    colors: ["#FF7F3F", "#60A5FA", "#A78BFA", "#34D399"],
    funnySentences: [
      "This is definitely my fancy version, I usually wear shorts and a band t-shirt 😎",
      "Did you know I prefer Windows + WSL over pure Linux? 🤔",
      "Did you know I'm a big fan of the Star Wars universe? 🌌",
      "Did you know I'm a big fan of the Lord of The Rings universe? ⚔️",
      "Did you know I've been a metal singer for a couple of years? 🎤",
      "Did you know I'm a combat sport amateur? 🥊",
      "Did you know I'm a huge fan of D&D (3.5 or 5th, 4 is not my jam)? 🎲",
      "Spaghetti code? I prefer pasta with ragù sauce 🍝",
      "My favorite drink is a pint of beer 🍺, what's yours?",
      "I'm not a football fan, I prefer rugby 🏉. What's your favorite sport?",
      "Yes, I've got tattos 🤘 (coverable, don't worry) and why should you worry anyway?",
      "My favorite film (or one of) is Gran Torino 🎥, what's yours?",
      "Yes, I've got stretched lobes. I'm a metalhead 🤘",
      "I do electronic music production 🎹, what's your favorite genre?",
      "One of my favourite videogames is The Witcher 3 🕹️, what's yours?",
      "Dear JavaScript, 0.1+0.2=0.30000000000000004, I'm not mad, just very disappointed.",
      "Docker enters in a bar, the bartender says: 'We don't serve containers here'.",
      "A DevOps, a SRE and a SysAdmin walk into a bar. The bartender says: 'What is this, some kind of joke?'",
      "Java is to JavaScript as car is to carpet.",
      "Confucio says 'Before you yell at your team, walk a mile in their shoes'.",
      "Sun Tzu said 'If you know the enemy and know yourself, you need not fear the result of a hundred deploys'.",
      "'I'm not a great programmer; I'm just a good programmer with great habits' - Kent Beck",
      "There are no 'best practices', just good ones.",
      "The best way to learn is to teach, that's why I mentor 👨‍🏫",
      "PHP since 8.0 is not that bad 🤷‍♂️",
      "I'm a big fan of Python 🐍",
      "I'm even a bigger fan of Go 🐹",
      "I play boardgames indeed, my friend. I can be a master too 🎲",
      "To write a recursive function you must first define a recursive function",
      "What does a SysAdmin say to a DevOps? 'Luke, I'm your father!'",
      "SREs are like Jedi Knights, they are the guardians of the force.",
      "What would you do with a million dollars? I'd invest them (crypto included) 💵",
      "C++ is C with classes. Prove me wrong 😎 (spoiler: you can't)",
      "echo 'Hello World'",
      "awk is like sed, but more powerful.",
      "No quote today, I'm too tired 🥱",
      "G note. When I was... a young dev... My father took me into the CI/CD to see a marching pipeline... 🎶",
      "I'm not a drummer but I air drum a lot 🥁",
      "How many SysAdmins does it take to change a lightbulb? None, they just tell the lightbulb to change itself 💡",
      "Have you got time to talk about our lord and saviour, the Cloud? ☁️",
      "I don't know what to put here, I'm not a comedian (yet).",
      "Have you ever tried to eat a clock? It's very time consuming 🕑",
      "I Google everything 🔍",
      "Once a PM said to me: 'I GANTT take this anymore.' 😫",
      "Stackoverflow is my best friend.",
      "How many times have you reloaded the page? I've lost count.",
      "Play the Stanley Parable, it's a great game.",
      "Waterfall? I prefer to swim 🏊‍♂️",
      "I'm not a coffein addict, but I drink a lot of coffee ☕",
      "And the winner is ...",
      "The best code is no code at all.",
      "'AI AI AI AI AI AI AI AI' cit. Sundar Pichai 2023 (CEO @ Google)",
      "Platform Engineering is the new DevOps.",
    ],
    firstPrinciple: "Software",
    firstLink: "/service/cto-as-a-service",
    secondPrinciple: "DevOps",
    secondLink: "/service/cloud-k8s-and-devops",
    thirdPrinciple: "SRE",
    thirdLink: "/service/sre-devsecops",
    fourthPrinciple: "Platform",
    fourthLink: "/service/devex-as-a-service",
    CTAs: ["Let's talk!", "Work with me", "Need a DevOps?", "Go cloud!", "Don't click here!", "Free call!"],
  },
};

export default heroData;
